# Description: Tensorflow Serving.

package(
    default_visibility = ["//net_http:__subpackages__"],
)

licenses(["notice"])

exports_files(["LICENSE"])

# open source marker; do not remove

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
            "g3doc/sitemap.md",
        ],
    ),
)
